import Head from "next/head";
import { client } from "../apolloClient";
import { gql } from "@apollo/client";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export const getStaticProps = async () => {
  const { data } = await client.query({
    query: gql`
      query {
        works {
          title
          slug
        }
      }
    `,
  });

  return {
    props: {
      data,
    },
  };
};
