import Head from "next/head";
import { client } from "../apolloClient";
import { gql } from "@apollo/client";
import HeaderSection from "../components/HeaderSection/HeaderSection";

export default function Home({ data }) {
  console.log(data.works[0]);
  return (
    <div>
      <Head>
        <title>Thomas Ranft Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Image /> */}
      <HeaderSection />
    </div>
  );
}

export const getStaticProps = async () => {
  const { data } = await client.query({
    query: gql`
      query {
        works {
          title
          slug
          coverImage {
            id
          }
        }
      }
    `,
  });

  return {
    props: {
      data,
    },
  };
};
